// =====================================================================
// src/lib/excelServer.ts
//
// Thin SPA wrapper around the server-side export API. Used by report
// sections to swap out their placeholder "خروجی اکسل به‌زودی" toast
// for a real .xlsx download triggered by the BFF.
//
// Security model: the SPA sends the user's Supabase JWT (Authorization
// Bearer); the server verifies and forwards it as a per-request scoped
// RPC client. No service-role key is ever embedded in this bundle.
//
// The endpoint URL comes from VITE_BFF_URL so prod and dev can point at
// different hosts (Render Web Service in prod, localhost:3000 in dev).
// If unset, falls back to a relative origin so the SPA calls itself
// — useful when both run on the same Render Static Site rewrite.
// =====================================================================

import { supabase } from '@/lib/supabase';

/**
 * The 12 live reports that the server registry knows how to export.
 *
 * - 6 LEGACY ids from the pre-redesign menu (Pass 1 retained them in
 *   `reportColumns.ts` so existing deep-links still resolve). The
 *   `registry.mjs` on the server has been kept for these IDs even
 *   though no SPA tile surfaces them anymore — a Pass 3 sweep will
 *   retire them.
 * - 6 NEW v3 ids from Pass-2 cutover: every one corresponds to a
 *   SECURITY INVOKER RPC in scripts/migrations/014_reporting_v3_enhancements.sql
 *   + dialect in services/export-api/registry.mjs.
 *
 * Adding a new id requires:
 *   - a corresponding rpcName entry in services/export-api/registry.mjs
 *   - the matching SQL function in scripts/migrations/014+ or a follow-up
 *   - the matching REPORT_CATALOG entry in src/types/report.types.ts
 *   - the matching REPORT_COLUMNS entry in src/components/reports/reportColumns.ts
 *
 * The TypeScript literal type forces all four to land in the same turn —
 * if you add a new id here without the others, the sections that
 * reference the missing id will fail to type-check.
 */
export type SupportedReportId =
  // 6 legacy ids (Pass 1 retained).
  | 'RPT_INVENTORY_VALUATION_SUMMARY'
  | 'RPT_INVENTORY_LEDGER'
  | 'RPT_CONSUMPTION_ANALYTICS'
  | 'RPT_INVENTORY_AGING'
  | 'RPT_PARETO_CLASSIFICATION'
  | 'RPT_SUPPLIERS'
  // 6 NEW v3 ids (Pass 2).
  | 'RPT_INVENTORY_STOCK'
  | 'RPT_CONSUMPTION_REPORT'
  | 'RPT_SALES_TRANSFERS'
  | 'RPT_PURCHASES'
  | 'RPT_PACKAGING'
  | 'RPT_REORDER_POINT';

/**
 * Report-specific filter payload. The server's `registry.mjs` knows how
 * to map this object to the appropriate RPC parameters; the SPA just
 * needs to forward the active `ReportFiltersState` (plus per-report
 * tweaks like `basis` or `dead_stock_days`).
 */
export type ReportExportFilters = Record<string, unknown>;

export interface ServerExportError extends Error {
  /** HTTP status code returned by the export endpoint, when known. */
  status?: number;
  /** Server-supplied error code, when known. */
  code?: string;
}

function makeError(message: string, status?: number, code?: string): ServerExportError {
  const err = new Error(message) as ServerExportError;
  err.status = status;
  err.code = code;
  return err;
}

/**
 * Triggers a download of the .xlsx blob generated by the export API.
 * Throws `ServerExportError` on auth / RBAC / RPC failures so callers
 * can surface the right message to the user.
 *
 * Usage:
 *   try {
 *     await triggerServerExport('RPT_PARETO_CLASSIFICATION', filters);
 *     toast.success('فایل اکسل آماده شد');
 *   } catch (e) {
 *     toast.error(...);
 *   }
 */
export async function triggerServerExport(
  reportId: SupportedReportId,
  filters: ReportExportFilters,
): Promise<{ fileName: string; rowCount: number | null }> {
  const { data: sessionData, error: sessionError } = await supabase.auth.getSession();
  const token = sessionData?.session?.access_token;
  if (sessionError || !token) {
    throw makeError(
      'برای دریافت خروجی اکسل ابتدا باید وارد حساب کاربری شوید.',
      401,
      'no_active_session',
    );
  }

  const baseUrl = resolveBffBaseUrl();
  const url = `${baseUrl}/api/export/${reportId}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(filters),
  });

  if (!response.ok) {
    let detail = '';
    let code = '';
    try {
      const payload = (await response.json()) as { error?: string; detail?: string };
      code = payload?.error ?? '';
      detail = payload?.detail ?? '';
    } catch {
      // Non-JSON response — fall through with the raw status text.
    }
    throw makeError(
      `خطا در دریافت خروجی اکسل (${response.status})${detail ? ` — ${detail}` : ''}`,
      response.status,
      code,
    );
  }

  const rowCountHeader = response.headers.get('X-Export-Row-Count');
  const contentDisposition = response.headers.get('Content-Disposition') ?? '';
  const fileName = parseFileName(contentDisposition) ?? deriveDefaultFileName(reportId);

  const blob = await response.blob();
  triggerBrowserDownload(blob, fileName);

  return {
    fileName,
    rowCount: rowCountHeader ? Number(rowCountHeader) : null,
  };
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

function resolveBffBaseUrl(): string {
  const envBase = import.meta.env.VITE_BFF_URL as string | undefined;
  if (envBase) return stripTrailingSlash(envBase);
  // Fall back to same-origin for static-site deployments that proxy /api
  // through to the API service.
  if (typeof window !== 'undefined' && window.location?.origin) {
    return window.location.origin;
  }
  return 'http://localhost:3000';
}

function stripTrailingSlash(s: string): string {
  return s.endsWith('/') ? s.slice(0, -1) : s;
}

function parseFileName(contentDisposition: string): string | null {
  const match = contentDisposition.match(/filename="?([^";]+)"?/i);
  return match ? match[1] : null;
}

function deriveDefaultFileName(reportId: string): string {
  const ts = new Date().toISOString().slice(0, 10);
  return `${reportId}_${ts}.xlsx`;
}

function triggerBrowserDownload(blob: Blob, fileName: string): void {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    // Non-browser runtime — typically the smoke-test harness or SSR.
    return;
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.rel = 'noopener';
  // Some browsers ignore clicks on detached <a>; append, click, remove.
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revocation so Safari has time to start the download.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
