-- Morvarid-FARM consolidated migration suite (generated from live schema)
-- 005_grants.sql - table + function privileges

-- ============ TABLE GRANTS ============
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.daily_voucher_lines TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.daily_voucher_lines TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.daily_vouchers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.daily_vouchers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_feed_formulas TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_feed_formulas TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_formula_items TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_formula_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_halls TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_halls TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_items TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farm_items TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farms TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.farms TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.inputs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.inputs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.inventory_transactions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.inventory_transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.profiles TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.suppliers TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.suppliers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.user_activity_logs TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.user_activity_logs TO authenticated;

-- ============ FUNCTION GRANTS / REVOKES ============
REVOKE ALL ON FUNCTION public.current_user_farm_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_user_farm_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_farm_id() TO anon;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;
REVOKE ALL ON FUNCTION public.is_admin_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin_user() TO anon;
REVOKE ALL ON FUNCTION public.is_current_user_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_current_user_admin() TO anon;
REVOKE ALL ON FUNCTION public.is_current_user_admin_or_supervisor() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_current_user_admin_or_supervisor() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_current_user_admin_or_supervisor() TO anon;
REVOKE ALL ON FUNCTION public.reporting_consumption_report_v3(date,date,uuid,text,text,uuid[],uuid[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_consumption_report_v3(date,date,uuid,text,text,uuid[],uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_consumption_report_v3(date,date,uuid,text,text,uuid[],uuid[]) TO anon;
REVOKE ALL ON FUNCTION public.reporting_consumption_summary(date,date,uuid,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_consumption_summary(date,date,uuid,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_consumption_summary(date,date,uuid,text,text) TO anon;
REVOKE ALL ON FUNCTION public.reporting_get_item_unit_price(uuid,uuid,date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_get_item_unit_price(uuid,uuid,date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_get_item_unit_price(uuid,uuid,date) TO anon;
REVOKE ALL ON FUNCTION public.reporting_inventory_balance_as_of(date,uuid,uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_balance_as_of(date,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_balance_as_of(date,uuid,uuid,text) TO anon;
REVOKE ALL ON FUNCTION public.reporting_inventory_ledger(uuid,uuid,text,date,date,text,timestamp with time zone,uuid,numeric,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_ledger(uuid,uuid,text,date,date,text,timestamp with time zone,uuid,numeric,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_ledger(uuid,uuid,text,date,date,text,timestamp with time zone,uuid,numeric,integer) TO anon;
REVOKE ALL ON FUNCTION public.reporting_inventory_stock(date,uuid,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_stock(date,uuid,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_inventory_stock(date,uuid,text,boolean) TO anon;
REVOKE ALL ON FUNCTION public.reporting_packaging_v3(date,date,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_packaging_v3(date,date,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_packaging_v3(date,date,uuid) TO anon;
REVOKE ALL ON FUNCTION public.reporting_pareto_classification(date,date,uuid,text,text,numeric,numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_pareto_classification(date,date,uuid,text,text,numeric,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_pareto_classification(date,date,uuid,text,text,numeric,numeric) TO anon;
REVOKE ALL ON FUNCTION public.reporting_purchases_v3(date,date,uuid,uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_purchases_v3(date,date,uuid,uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_purchases_v3(date,date,uuid,uuid,uuid) TO anon;
REVOKE ALL ON FUNCTION public.reporting_reorder_point_v3(uuid,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_reorder_point_v3(uuid,text,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_reorder_point_v3(uuid,text,text,boolean) TO anon;
REVOKE ALL ON FUNCTION public.reporting_sales_transfers_v3(date,date,uuid,uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_sales_transfers_v3(date,date,uuid,uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_sales_transfers_v3(date,date,uuid,uuid,text) TO anon;
REVOKE ALL ON FUNCTION public.reporting_suppliers_list(uuid,text,boolean,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reporting_suppliers_list(uuid,text,boolean,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reporting_suppliers_list(uuid,text,boolean,text) TO anon;
REVOKE ALL ON FUNCTION public.revert_daily_sheet(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.revert_daily_sheet(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_create_farm(text,text,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_create_farm(text,text,text,text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_create_farm_item(uuid,text,text,text,integer,numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_create_farm_item(uuid,text,text,text,integer,numeric) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_create_formula(uuid,integer,text,numeric,boolean,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_create_formula(uuid,integer,text,numeric,boolean,jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_create_input(text,text,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_create_input(text,text,text,text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_create_supplier(text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_create_supplier(text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_farm(uuid,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_farm(uuid,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_farm_item(uuid,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_farm_item(uuid,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_formula(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_formula(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_input(uuid,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_input(uuid,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_inventory_txn(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_inventory_txn(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_delete_supplier(uuid,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_delete_supplier(uuid,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_duplicate_formula(uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_duplicate_formula(uuid,integer) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_get_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_get_profile(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_hard_delete_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_hard_delete_profile(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_log_activity(text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_log_activity(text,text,text) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_soft_delete_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_soft_delete_profile(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_toggle_farm(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_toggle_farm(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_toggle_formula(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_toggle_formula(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_toggle_input(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_toggle_input(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_toggle_profile(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_toggle_profile(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_toggle_supplier(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_toggle_supplier(uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_update_farm(uuid,text,text,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_update_farm(uuid,text,text,text,text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_update_formula(uuid,text,numeric,boolean,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_update_formula(uuid,text,numeric,boolean,jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_update_input(uuid,text,text,text,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_update_input(uuid,text,text,text,text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_update_inventory_txn(uuid,numeric,numeric,date,text,text,numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_update_inventory_txn(uuid,numeric,numeric,date,text,text,numeric) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_update_supplier(uuid,text,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_update_supplier(uuid,text,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_admin_upsert_profile(uuid,text,text,text,text,text,uuid,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_admin_upsert_profile(uuid,text,text,text,text,text,uuid,boolean) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_create_inventory_txn(uuid,uuid,date,text,numeric,numeric,numeric,text,text,uuid,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_create_inventory_txn(uuid,uuid,date,text,numeric,numeric,numeric,text,text,uuid,text,text) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_get_or_create_draft_voucher(uuid,date,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_get_or_create_draft_voucher(uuid,date,text) TO authenticated;
REVOKE ALL ON FUNCTION public.rpc_initial_stock_exists(uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_initial_stock_exists(uuid,uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_initial_stock_exists(uuid,uuid) TO anon;
REVOKE ALL ON FUNCTION public.rpc_supplier_usage_count(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_supplier_usage_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.rpc_supplier_usage_count(uuid) TO anon;
REVOKE ALL ON FUNCTION public.rpc_upsert_voucher_line(uuid,uuid,text,numeric,text,numeric,numeric,text,jsonb,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.rpc_upsert_voucher_line(uuid,uuid,text,numeric,text,numeric,numeric,text,jsonb,uuid) TO authenticated;
REVOKE ALL ON FUNCTION public.save_daily_sheet(uuid,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.save_daily_sheet(uuid,jsonb) TO authenticated;
REVOKE ALL ON FUNCTION public.submit_daily_voucher(uuid,uuid,date,jsonb,boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_daily_voucher(uuid,uuid,date,jsonb,boolean) TO authenticated;
